import type { AppPage } from "@/shared";
import {
	HomePage,
	SignUp,
	SignIn,
	Profile,
	Projects,
	Freelancers,
} from "@/pages/index";
export const PageRoutes: AppPage[] = [
	{
		path: "/",
		label: "Главная",
		component: HomePage,
		showInNavbar: true,
		access: "public",
	},
	{
		path: "/sign-up",
		label: "Регистрация",
		component: SignUp,
		showInNavbar: true,
		access: "guest",
	},
	{
		path: "/sign-in",
		label: "Вход",
		component: SignIn,
		showInNavbar: true,
		access: "guest",
	},
	{
		path: "/profile",
		label: "Профиль",
		component: Profile,
		showInNavbar: true,
		access: "private",
	},
	{
		path: "/projects/new",
		label: "Новый заказ",
		component: Projects,
		showInNavbar: false,
		access: "client",
	},
	{
		path: "/projects/:projectId",
		label: "Заказ",
		component: Projects,
		showInNavbar: false,
		access: "private",
	},
	{
		path: "/freelancers",
		label: "Фрилансеры",
		component: Freelancers,
		showInNavbar: true,
		access: "client",
	},
	{
		path: "/projects",
		label: "Заказы",
		component: Projects,
		showInNavbar: true,
		access: "public",
	},
	{
		path: "/projects/new",
		label: "Новый заказ",
		component: Projects,
		showInNavbar: false,
		access: "client",
	},
	{
		path: "/projects/:projectId",
		label: "Заказ",
		component: Projects,
		showInNavbar: false,
		access: "private",
	},
];
