import type { AppPage } from "@/shared";
import {
	HomePage,
	SignUp,
	SignIn,
	RecoveryPassword,
	ResetPassword,
	Profile,
	Projects,
	Freelancers,
	Admin,
} from "@/pages/index";
export const PageRoutes: AppPage[] = [
	{
		path: "/",
		label: "Главная",
		component: HomePage,
		showInNavbar: true,
		access: "public",
	},
	{
		path: "/sign-up",
		label: "Регистрация",
		component: SignUp,
		showInNavbar: true,
		access: "guest",
	},
	{
		path: "/sign-in",
		label: "Вход",
		component: SignIn,
		showInNavbar: true,
		access: "guest",
	},
	{
		path: "/recovery-password",
		label: "Восстановление пароля",
		component: RecoveryPassword,
		showInNavbar: false,
		access: "guest",
	},
	{
		path: "/recovery-password/confirm",
		label: "Подтверждение восстановления",
		component: ResetPassword,
		showInNavbar: false,
		access: "guest",
	},
	{
		path: "/profile",
		label: "Профиль",
		component: Profile,
		showInNavbar: true,
		access: "private",
	},
	{
		path: "/admin",
		label: "Админ",
		component: Admin,
		showInNavbar: true,
		access: "Admin",
	},
	{
		path: "/projects/new",
		label: "Новый заказ",
		component: Projects,
		showInNavbar: false,
		access: "Client",
	},
	{
		path: "/projects/:projectId",
		label: "Заказ",
		component: Projects,
		showInNavbar: false,
		access: "private",
	},
	{
		path: "/freelancers",
		label: "Фрилансеры",
		component: Freelancers,
		showInNavbar: true,
		access: "Client",
	},
	{
		path: "/projects",
		label: "Заказы",
		component: Projects,
		showInNavbar: true,
		access: "public",
	},
	// {
	// 	path: "/projects/new",
	// 	label: "Новый заказ",
	// 	component: Projects,
	// 	showInNavbar: false,
	// 	access: "client",
	// },
	// {
	// 	path: "/projects/:projectId",
	// 	label: "Заказ",
	// 	component: Projects,
	// 	showInNavbar: false,
	// 	access: "private",
	// },
];
